SKILL_VOCABULARY = [
    "python",
    "fastapi",
    "django",
    "flask",
    "machine learning",
    "deep learning",
    "nlp",
    "rest api",
    "graphql",
    "sql",
    "nosql",
    "docker",
    "kubernetes",
    "aws",
    "gcp",
    "azure",
    "embeddings",
    "vector database",
    "faiss",
    "chromadb",
    "pytorch",
    "tensorflow",
    "scikit-learn"
]
